<a href="https://colab.research.google.com/github/sriharsha2006/Machine_Learning/blob/main/KNN/KNN_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import numpy as np


In [3]:
url="https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
data=pd.read_csv(url)
data.head()


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
x=data.drop("species",axis=1)
y=data["species"]


In [5]:
trainx,testx,trainy,testy=train_test_split(x,y,test_size=0.2)


In [6]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(trainx,trainy)

KNeighborsClassifier()

In [7]:
pred=knn.predict(testx)

In [8]:
print(confusion_matrix(testy,pred))
print(classification_report(testy,pred))
print(accuracy_score(testy,pred))

[[12  0  0]
 [ 0 12  0]
 [ 0  0  6]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       1.00      1.00      1.00        12
   virginica       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

1.0


In [9]:
plt.scatter(data["sepal_length"],data["sepal_width"],c=np.random.rand(len(data)))
plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.title("Iris Sepal Scatter (randomized)",color="orange")
plt.grid(True)
plt.show()